name: Sync Image Paths

on:
  push:
    branches:
      - main

jobs:
  sync-images:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Git
      run: |
        git config --global user.email "songwqs@gmail.com"
        git config --global user.name "songwqs"

    - name: Initialize Git
      run: git init

    - name: Remote add origin
      run: git remote add origin https://github.com/songwqs/songw_Actions.git

    - name: Fetch only the needed directory
      run: |
        git fetch origin main:cicd-sync
        git checkout cicd-sync -- cdnImg/hacg/image_paths.json

    - name: Commit and push changes
      run: |
        git add cdnImg/hacg/image_paths.json
        git commit -m "Sync image_paths.json"
        git push https://${{ secrets.RAW_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
