name: Sync Image Paths

on:
  push:
    branches:
      - main

jobs:
  sync-images:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Git
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"

    - name: Fetch only the needed directory
      run: |
        mkdir -p cdnImg/hacg
        curl -sSL -o cdnImg/hacg/image_paths.json https://raw.githubusercontent.com/songwqs/songw_Actions/main/cdnImg/hacg/image_paths.json

    - name: Commit and push changes
      run: |
        cd cdnImg
        git init
        git add hacg/image_paths.json
        git commit -m "Sync image_paths.json"
        git remote add origin https://${{ secrets.RAW_TOKEN }}@github.com/${{ github.repository }}.git
        git push -u origin main
