name: Sync Image Paths

on:
  push:
    branches:
      - main

jobs:
  sync-images:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Git
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"

    - name: Fetch only the needed directory
      run: |
        mkdir -p cdnImg/hacg
        curl -sSL -o cdnImg/hacg/image_paths.json https://raw.githubusercontent.com/songwqs/songw_Actions/main/cdnImg/hacg/image_paths.json

    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_SONGW_ACTIONS" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
      env:
          SSH_SONGW_ACTIONS: ${{ secrets.SSH_SONGW_ACTIONS }}
    - name: Commit changes
      run: |
        cd cdnImg
        git init
        git add hacg/image_paths.json
        git commit -m "Sync image_paths.json"

    - name: Force push changes to main
      run: |
        cd cdnImg
        git remote add origin git@github.com:songwqs/songw_Actions.git
        git push -f origin HEAD:refs/heads/main
